### PR TITLE
Propagate all error fields

### LINKED ISSUE #150: Return extra fields when an error occurs
When an error occurs during the request, we currently send back two things, the http status code and a message such as `{"message":"Incorrect password"}`. The `code`, `errno` and `error` from the `AppError` are thrown away.

Here is where an error is sent back: https://github.com/mozilla/fxa-auth-db-server/blob/master/index.js#L50

But in restify, only the `message` is extracted from from the `AppError` (since `AppError` inherits from `Error`): https://github.com/restify/node-restify/blob/master/lib/formatters/json.js#L16-L18

This may or may not have been intentional but it seems that those extra fields would be useful to the auth server in some circumstances. It may be best to explicitly return them if they exist on the error object.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #150.

@chilts, was this what you had in mind or have I got the wrong end of the stick?

### CODE REVIEW

File: test/backend/remote.js [hunk 1]
```diff
@@ -44,7 +44,9 @@ function respOkEmpty(t, r) {
 // Takes the test object (t) and the error object (err).
 function testNotFound(t, err) {
   t.equal(err.statusCode, 404, 'returns a 404')
-  t.deepEqual(err.body, { message : 'Not Found' }, 'Object contains no other fields')
+  t.deepEqual(err.body, {
+    message : 'Not Found', errno: 116, error: 'Not Found', code: 404
```
Comment (pdehaan) [inline test/backend/remote.js]: nit: maybe put each of these props on a separate line for readability.
Also, remove the stray space between `message` and `:` since our linter may blow up (but not sure in this exact repo).

**Comment by chilts** [comment]
Hi @philbooth, this looks great. Perhaps squash the commit since it probably makes more sense as just one change (esp. because the first test change is being overwritten by the second commit).

In your squashed commit, you could also add a "Fixes #151" so it refers to this issue. Thanks. :)

**Comment by philbooth** [comment]
Done. :)

**Comment by chilts** [comment]
Perfect. Yes, that's pretty much what I was thinking.

I'm just gonna get @rfk to also look over this ... since we're returning extra stuff to the auth server, I think this is totally backwards compatible. Ryan, does that seem ok to you?

Two other things we should do after this has been merged is to make sure the auth server expects these fields:

1. Perhaps add this check for `errno` back in (now that we are returning it) - https://github.com/mozilla/fxa-auth-server/pull/964/files#r32193066
2. For any fields we use in the auth-server, we should also add tests that the auth server expects them and expects them to be the correct value.

**Comment by rfk** [comment]
LGTM; actually I'm surprised it worked out quite that neatly, but very happy to see.  If this breaks the auth-server, that's something in the auth-server that needs fixing.
