### PR TITLE
fix(db): ensure that requests for bad paths are logged

### LINKED ISSUE #144: requests for unknown paths are not logged by the app
If you make this request:
```
$ curl -X GET -s -D - http://127.0.0.1:8000/foobar/61626361626461622b736f69756f696f697540666173746d61696c2e666d
HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 123
Date: Thu, 04 Jun 2015 02:07:32 GMT
Connection: keep-alive

{"code":"ResourceNotFound","message":"/foobar/61626361626461622b736f69756f696f697540666173746d61696c2e666d does not exist"}
```

it is not logged in the application log. Since these servers are not publically exposed to the internet, any request for an unknown path is a serious error somewhere.

### PR DESCRIPTION
**Pull request by philbooth**
@chilts @rfk

Revised from #154, fixes #144, depends on https://github.com/mozilla/fxa-auth-db-mem/pull/39.

Improves on the previous PR in two ways:

1. Uses restify's `NotFound` event to catch all requests to unknown paths.
2. Uses the linked fx-auth-db-mem PR to test that the server emits the failure event as expected.

Any good?

### CODE REVIEW

**Comment by rfk** [comment]
Agreed this is a better approach.

File: test/backend/remote.js [hunk 1]
```diff
@@ -52,10 +52,26 @@ function testNotFound(t, err) {
...
+    serverOn('failure', t.pass.bind(t, 'The server emitted the failure event'))
+  }
+}
+
 // To run these tests from a new backend, create a DB instance, start a test server
 // and pass the config containing the connection params to this function. The tests
-// will run against that server.
-module.exports = function(cfg) {
+// will run against that server. Optional second argument is the bound server.on
+// function, to enable tests to listen for emitted server events.
```
Comment (rfk) [inline test/backend/remote.js]: Does this need to be optional?  I think I'd be fine to just always pass it in.

File: test/backend/remote.js [hunk 2]
```diff
@@ -551,6 +567,81 @@ module.exports = function(cfg) {
   )
 
   test(
+    'get an unknown path',
+    function (t) {
+      testFailureEvent(t, serverOn, 2)
```
Comment (rfk) [inline test/backend/remote.js]: I like not repeating yourself in each test, but something about the way this is called seems to obscure its intention.  I wonder if we could do something like:

```
t.plan(3)
failures = captureFailureEvents(server)
client.getThen('/foo').then(
  ...
).then( function(err) {
  testNotFound(t, err)
  t.equal(failures.length, 1, "emitted the failure event")
)}
```

What's nice about this is it keeps the `t.plan` and `t.equal` calls locally in the test, so you can get a sense of the entire flow of the test just by looking locally in that function.  Thoughts?

**Comment by rfk** [comment]
Otherwise, looking good!

File: test/backend/remote.js (hunk 1 above)
Comment (philbooth) [inline test/backend/remote.js]: Only reason I made it optional was so that the tests wouldn't fail if anyone updates this repo without also having updated `fxa-auth-db-mem`. But maybe that's a feature.

File: test/backend/remote.js (hunk 2 above)
Comment (philbooth) [inline test/backend/remote.js]: Yep, makes sense. :)

**Comment by philbooth** [comment]
@rfk pushed
